# Generated by Django 5.2.7 on 2025-10-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("Category_slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=1000)),
                (
                    "cat_image",
                    models.ImageField(blank=True, upload_to="images/categories/"),
                ),
            ],
        ),
    ]
