# Generated by Django 5.2.7 on 2025-10-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="Category_slug",
            new_name="slug",
        ),
    ]
